### ISSUE TITLE
pip install reproject raises Type() error

### ISSUE THREAD

**Issue by indiajoe** [astrofrog/reproject#142]
When I tried to install reproject, I got the following error

```
$ pip install reproject
Collecting reproject
  Downloading reproject-0.3.2.tar.gz (662kB)
    100% |████████████████████████████████| 665kB 8.2MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-qMVQAr/reproject/setup.py", line 18, in <module>
        from astropy_helpers.setup_helpers import (register_commands, get_debug_option,
      File "/tmp/pip-build-qMVQAr/reproject/.eggs/astropy_helpers-0.4.8-py2.7.egg/astropy_helpers/setup_helpers.py", line 56, in <module>
        from sphinx.setup_command import BuildDoc as SphinxBuildDoc
      File "/home/joe/PyNEIDenv/lib/python2.7/site-packages/sphinx/setup_command.py", line 23, in <module>
        from sphinx.application import Sphinx
      File "/home/joe/PyNEIDenv/lib/python2.7/site-packages/sphinx/application.py", line 33, in <module>
        from sphinx.environment import BuildEnvironment
      File "/home/joe/PyNEIDenv/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 46, in <module>
        from sphinx.util.websupport import is_commentable
      File "/home/joe/PyNEIDenv/lib/python2.7/site-packages/sphinx/util/websupport.py", line 11, in <module>
        from sphinxcontrib.websupport.utils import is_commentable  # NOQA
      File "/home/joe/PyNEIDenv/lib/python2.7/site-packages/sphinxcontrib/websupport/__init__.py", line 15, in <module>
        from sphinxcontrib.websupport.core import WebSupport  # NOQA
      File "/home/joe/PyNEIDenv/lib/python2.7/site-packages/sphinxcontrib/websupport/core.py", line 17, in <module>
        from jinja2 import Environment, FileSystemLoader
      File "/home/joe/PyNEIDenv/lib/python2.7/site-packages/jinja2/__init__.py", line 33, in <module>
        from jinja2.environment import Environment, Template
      File "/home/joe/PyNEIDenv/lib/python2.7/site-packages/jinja2/environment.py", line 15, in <module>
        from jinja2 import nodes
      File "/home/joe/PyNEIDenv/lib/python2.7/site-packages/jinja2/nodes.py", line 19, in <module>
        from jinja2.utils import Markup
      File "/home/joe/PyNEIDenv/lib/python2.7/site-packages/jinja2/utils.py", line 486, in <module>
        MutableMapping.register(LRUCache)
      File "/home/joe/PyNEIDenv/lib64/python2.7/abc.py", line 109, in register
        if issubclass(subclass, cls):
      File "/home/joe/PyNEIDenv/lib64/python2.7/abc.py", line 180, in __subclasscheck__
        if issubclass(subclass, scls):
      File "/home/joe/PyNEIDenv/lib/python2.7/site-packages/typing.py", line 1265, in __subclasscheck__
        return super(GenericMeta, self).__subclasscheck__(cls)
    TypeError: must be type, not None
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-qMVQAr/reproject/

```

This issue seems to be very similar to the error reported by @bsipocz in this thread https://github.com/sphinx-doc/sphinx/issues/3766
Also probably related to this open issue: https://github.com/sphinx-doc/sphinx/issues/3976
I made sure everything else, like astropy, sphinx, jinja2 are all the latest.

**Comment by indiajoe** [comment]
Update: Downgrading sphinx to 1.5 fixed the issue for now.

**Comment by bsipocz** [comment]
This is weird, as reproject 0.3.2 should be compatible with the latest sphinx.

**Comment by bsipocz** [comment]
Oh, I take it back, it seems that 0.3.2 was made from a bugfix branch that doesn't have the relevant astopy-helpers update backported. 

@astrofrog - is there an ETA for the next release from the master branch?

**Comment by astrofrog** [comment]
@bsipocz - I'll do a release very shortly, @Cadair and I just need to finish up some changes.

**Comment by astrofrog** [comment]
@indiajoe - just FYI, reproject v0.4 has been released and should fix this
